#include "slint.h"
#include "gui.slint"  // Generated by Slint compiler
#include "pacmkr/gui_backend.h"

#include <QApplication>
#include <iostream>

/// Custom Slint component that wraps the C++ Backend
class MainWindowImpl : public pacmkr::gui::MainWindow {
public:
    MainWindowImpl() : backend_(std::make_unique<pacmkr::gui::Backend>()) {
        // Initialize UI state
        set_searching(false);
        set_build_in_progress(false);
        set_progress_value(0);
        set_log_output("");
        set_build_status("");

        // Connect callbacks
        on_trigger_search([this]() {
            trigger_search_impl();
        });

        on_refresh_cache([this]() {
            refresh_cache_impl();
        });

        on_select_package([this](auto item) {
            select_package_impl(item);
        });

        on_add_to_build_queue([this](auto item) {
            add_to_build_queue_impl(item);
        });

        on_view_details([this](auto item) {
            view_details_impl(item);
        });

        on_start_build([this]() {
            start_build_impl();
        });

        on_cancel_build([this]() {
            cancel_build_impl();
        });
    }

private:
    std::unique_ptr<pacmkr::gui::Backend> backend_;
    std::vector<SearchResult> search_results_;  // Cached results

    // ─── Search Operations ────────────────────────────────────────

    void trigger_search_impl() {
        auto query = get_search_query();
        if (query.empty()) return;

        set_searching(true);
        update_build_status("Searching...");

        // Run search in background (Slint callbacks run on UI thread)
        std::thread([this, query]() {
            try {
                auto results = backend_->search(query);

                // Update UI on main thread
                slint::invoke_from_event_loop([this, results]() {
                    search_results_ = results;

                    // Convert to Slint model
                    set_search_results(convert_to_slint_model(results));

                    set_searching(false);
                    update_build_status(results.empty() ? "No results found" :
                                        std::to_string(results.size()) + " packages found");
                });
            } catch (const std::exception& e) {
                slint::invoke_from_event_loop([this, msg = std::string(e.what())]() {
                    set_searching(false);
                    update_build_status("Search error: " + msg);
                });
            }
        }).detach();
    }

    void refresh_cache_impl() {
        set_searching(true);
        update_build_status("Refreshing AUR cache...");

        std::thread([this]() {
            try {
                backend_->refresh_cache();

                slint::invoke_from_event_loop([this]() {
                    set_searching(false);
                    update_build_status("AUR cache refreshed");

                    // Re-run search if there's a query
                    auto query = get_search_query();
                    if (!query.empty()) {
                        trigger_search_impl();
                    }
                });
            } catch (...) {
                slint::invoke_from_event_loop([this]() {
                    set_searching(false);
                    update_build_status("Cache refresh failed");
                });
            }
        }).detach();
    }

    // ─── Package Selection ────────────────────────────────────────

    void select_package_impl(auto item) {
        auto search_result = convert_from_slint_item(item);
        set_selected_package(convert_to_slint_model({search_result}));

        // Update info panel with package details
        std::thread([this, name = search_result.name]() {
            try {
                auto info = backend_->get_package_info(name);

                slint::invoke_from_event_loop([this, info]() {
                    auto result_list = convert_to_slint_model({info});
                    set_selected_package(result_list);
                });
            } catch (...) {}
        }).detach();
    }

    void add_to_build_queue_impl(auto item) {
        auto search_result = convert_from_slint_item(item);

        slint::invoke_from_event_loop([this, result = search_result]() {
            // Add to build queue (simplified - in real app, use a proper list model)
            update_build_status("Added " + result.name + " to build queue");

            // Note: Full implementation would maintain a BuildQueue model
        });
    }

    void view_details_impl(auto item) {
        auto search_result = convert_from_slint_item(item);

        std::thread([this, name = search_result.name]() {
            try {
                auto info = backend_->get_package_info(name);

                slint::invoke_from_event_loop([this, info]() {
                    auto result_list = convert_to_slint_model({info});
                    set_selected_package(result_list);
                });
            } catch (...) {}
        }).detach();
    }

    // ─── Build Operations ─────────────────────────────────────────

    void start_build_impl() {
        if (backend_->is_building()) return;

        set_build_in_progress(true);
        update_build_status("Starting build...");
        clear_log();

        // Get build targets (simplified - in real app, use proper queue model)
        std::vector<SearchResult> targets = {{"example", "1.0", "aur", "Example package", false}};

        // Setup callbacks for progress and log updates
        auto progress_cb = [this](int percent, const std::string& status) {
            slint::invoke_from_event_loop([percent, status]() {
                set_progress_value(percent);
                update_build_status(status);
            });
        };

        auto log_cb = [this](const std::string& line) {
            slint::invoke_from_event_loop([line]() {
                append_log(line + "\n");
            });
        };

        // Start build in background
        backend_->start_build(targets, progress_cb, log_cb);
    }

    void cancel_build_impl() {
        backend_->cancel_build();
        set_build_in_progress(false);
        update_build_status("Build cancelled");
    }

    // ─── Helper Functions ─────────────────────────────────────────

    void update_build_status(const std::string& status) {
        set_build_status(status);
    }

    void clear_log() {
        set_log_output("");
    }

    void append_log(const std::string& line) {
        auto current = get_log_output();
        set_log_output(current + line);
    }

    // ─── Slint Model Conversion Helpers ───────────────────────────

    /// Convert C++ SearchResult to Slint model (simplified)
    slint::VectorModel<std::unique_ptr<SearchResultItem>> convert_to_slint_model(
        const std::vector<SearchResult>& results) {

        auto model = std::make_unique<slint::VectorModel<std::unique_ptr<SearchResultItem>>>();

        for (auto& r : results) {
            auto item = std::make_unique<SearchResultItem>();
            item->set_name(r.name);
            item->set_version(r.version);
            item->set_origin(r.origin == "aur" ? "aur" : "repo");
            item->set_description(r.description);
            item->set_is_out_of_date(r.is_out_of_date);

            model->push_back(std::move(item));
        }

        return slint::VectorModel<std::unique_ptr<SearchResultItem>>(std::move(model));
    }

    /// Convert Slint item to C++ SearchResult (simplified)
    SearchResult convert_from_slint_item(auto item) {
        SearchResult result{};
        result.name = item->get_name();
        result.version = item->get_version();
        result.origin = item->get_origin();
        result.description = item->get_description();
        result.is_out_of_date = item->get_is_out_of_date();
        return result;
    }
};

int main(int argc, char* argv[]) {
    // Initialize Qt application
    QApplication app(argc, argv);

    // Create and show Slint window
    auto window = std::make_unique<MainWindowImpl>();
    window->show();

    return app.exec();
}
