#include "pacmkr/package.h"
#include "pacmkr/pkgbuild.h"
#include "pacmkr/error.h"

#include <fstream>
#include <filesystem>
#include <iostream>
#include <algorithm>

namespace pacmkr::package {

namespace {

uint64_t calc_dir_size(const std::filesystem::path& path) {
    uint64_t size = 0;
    try {
        for (auto& entry : std::filesystem::recursive_directory_iterator(path)) {
            if (entry.is_regular_file()) {
                size += std::filesystem::file_size(entry.path());
            }
        }
    } catch (...) {}
    return size;
}

std::string escape_pkginfo(const std::string& s) {
    std::string result;
    for (char c : s) {
        if (c == '\n') result += ' ';
        else if (!std::isspace(static_cast<unsigned char>(c))) result += c;
    }
    // Trim
    auto start = result.find_first_not_of(" \t");
    if (start != std::string::npos) result = result.substr(start);
    auto end = result.find_last_not_of(" \t");
    if (end != std::string::npos) result = result.substr(0, end + 1);
    return result;
}

} // anonymous

Package Package::make(const std::string& name, const std::string& version,
                      const std::string& arch, const std::filesystem::path& dest_dir) {
    Package pkg;
    pkg.name = name;
    pkg.version = version;
    pkg.arch = arch;
    pkg.dest = dest_dir / (name + "-" + version + ".pkg.tar.zst");
    return pkg;
}

void Package::write_pkginfo(const pkgbuild::Pkgbuild& pb,
                            const std::filesystem::path& pkgdir,
                            const std::string& packager,
                            uint64_t builddate) const {
    std::ofstream out(pkgdir / ".PKGINFO");
    if (!out) throw package_error("Cannot write .PKGINFO");

    out << "# Generated by pacmkr\n";
    out << "pkgname = " << name << "\n";
    auto pb_base = pb.pkgbase_opt.has_value() ? *pb.pkgbase_opt : (pb.pkgname.empty() ? "unknown" : pb.pkgname[0]);
    out << "pkgbase = " << pb_base << "\n";
    out << "pkgver = " << version << "\n";
    out << "pkgdesc = " << escape_pkginfo(pb.desc) << "\n";
    out << "url = " << escape_pkginfo(pb.url) << "\n";
    out << "builddate = " << builddate << "\n";
    out << "packager = " << packager << "\n";
    out << "size = " << calc_dir_size(pkgdir) << "\n";
    out << "arch = " << arch << "\n";

    for (auto& lic : pb.license)  out << "license = " << lic << "\n";
    for (auto& dep : pb.depends)  out << "depend = " << dep << "\n";
    for (auto& dep : pb.makedepends) out << "makedepend = " << dep << "\n";
    for (auto& dep : pb.checkdepends) out << "checkdepend = " << dep << "\n";
    for (auto& dep : pb.optdepends) out << "optdepend = " << escape_pkginfo(dep) << "\n";
    for (auto& g : pb.groups)     out << "group = " << g << "\n";
    for (auto& c : pb.conflicts)  out << "conflict = " << c << "\n";
    for (auto& p : pb.provides)   out << "provides = " << p << "\n";
    for (auto& r : pb.replaces)   out << "replaces = " << r << "\n";
    for (auto& b : pb.backup)     out << "backup = " << b << "\n";

    out.close();
}

void Package::create_archive(const std::filesystem::path& pkgdir) const {
    std::cout << "==> Compressing package...\n";

    // Use bsdtar for Arch Linux compatibility
    int rc = std::system(
        ("bsdtar --no-fflags --no-read-sparse -cJf \"" +
         dest.string() + "\" -C \"" + pkgdir.string() + "\" . 2>&1").c_str());

    if (rc != 0) {
        throw package_error("bsdtar failed to create package archive");
    }

    std::cout << "==> Package created: " << dest.string() << "\n";
}

uint64_t dir_size(const std::filesystem::path& path) {
    return calc_dir_size(path);
}

} // namespace pacmkr::package
